baseURL = 'https://informalis.github.io/'
languageCode = 'en-us'
title = "Cass's RPG nonsense"
#theme = "console"
theme = "zen"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  breadcrumbSections = [ "pathfinder", "delta-green" ]
  mainSections = [ "" ]
  logo = false
  menuInHeader = true

[languages.en]
weight = 1
languageName = "English"
languageCode = "en-US"
contentDir = "content/en"

[[languages.en.menu.main]]
Name = "Home"
weight = -10
pageRef = "/"

[[languages.en.menu.main]]
Name = "Pathfinder"
weight = 2
pageRef = "/pathfinder"

[[languages.en.menu.main]]
Name = "Delta Green"
weight = 4
pageRef = "/delta-green/"

# [[languages.en.menu.main]]
# Name = "Products"
# weight = 6
# pageRef = "/products/"

# [[languages.en.menu.main]]
# Name = "Misc"
# weight = 8
# pageRef = "/misc/"

# [[languages.en.menu.main]]
# Name = "Search"
# weight = 10
# pageRef = "/search/"

# [[languages.en.menu.main]]
# Name = "Contact"
# weight = 12
# pageRef = "/contact/"
